- mas/api/api.go
- mas/db/ingest.sh
- mas/db/schema.sql
- mas/db/shard.sql
- mas/db/shard_create.sh
- mas/db/shard_exists.sh
- mas/db/shard_refresh.sh
- mas/db/shard_reset.sh
The schema and associated shell scripts hardcode `nci` as the PostgreSQL username and database name.  This patch renames all such instances to `mas`. The table names (eg, `nci_foo`) have not yet been dealt with. That will be addressed separately.
> Rename 'nci' to 'mas' for username and database name

- mas/db/schema.sql
Use the `\echo` command in `psql` to print a reassuring message on the console. This makes it clear that the operation successfully concluded.
> schema.sql: Echo "Done!" at the end to make success clear.

- Makefile.in
Make sure shell scripts are installed as executable.
> Install .sql files as mode 644 and shell scripts as mode 755

- templates/WCS_DescribeCoverage.tpl
@bje- I added netcdf as the supported file format for WCS DescribeCoverage endpoint. This fixed bug https://github.com/nci/gsky/issues/26 Please review and merge the changes.
> added netcdf to the supported file format of WCS

- grpc_server/grpc_server.go
- mas/api/api.go
- processor/tile_grpc.go
I have started running `go vet` over the Go code. Most directories are clean, but there are a few warnings to fix. Here are the first three:
```
$ go vet api.go
api.go:116: unreachable code
$ go vet tile_grpc.go
tile_grpc.go:85: arg rasterTime for printf verb %d of wrong type: time.Time
$ go vet grpc_server.go
grpc_server.go:31: github.com/nci/gsky/grpc_server/gdalservice.Task composite literal uses unkeyed fields
```
> Remove unreachable code in api.go

- ows.go
Fix potential context leaks found by `go vet`:
```    
the ctxCancel function is not used on all paths (possible context leak)
this return statement may be reached without using the ctxCancel var ...
```
I re-arranged the code slightly from the original attempt to fix this just to minimise the diffs. This one should be simple to review.
> Fix potential context leaks found by go vet

- templates/WMS_GetCapabilities.tpl
@bje- I added add conditional check to see if legend path is set is the config file. If not set, we will not send legend in the GetCapabilities call. This fixed https://github.com/nci/gsky/issues/15 and probably https://github.com/nci/gsky/issues/27 Howerver, https://github.com/nci/gsky/issues/27 requires additional testing using QGIS which I do not have at the moment. Please review and merge the changes.
> added conditional check for the existence layer legend path

- templates/WMS_GetCapabilities.tpl
@bje- I removed jpeg and gif format for WMS output as the current code doesn't work with them. This fixed https://github.com/nci/gsky/issues/10 Please review and merge the changes.
> removed jpeg and gif format

- Makefile.in
This change puts `concurrent.c` in a subdirectory out of the way of the Go source code. `go get` (and possibly other tools) complain if `.c` files are in the Go project directory.
> Keep concurrent.c out of the way of the Go source

- utils/wms.go
@bje- I added support for I and J http request parameters. I and J in WMS 1.3.0 work in the same way as X and Y in WMS 1.1.1 so I simply convert them into X and Y if they're present. This should fix https://github.com/nci/gsky/issues/14
> added I and J into http request parameters for GetFeatureInfo()

- ows.go
@bje- If time is not specified in the http request, we now use last known date instead of first known date in order to be standard compliant. This fixed https://github.com/nci/gsky/issues/12 Please review and merge the changes.
> changed to use last known date if time not specified

- Makefile.in
It is necessary to pass `CGO_CFLAGS` to `go get` so that `go get` works with CGo code.
> Makefile.in: Pass CGO_CFLAGS to 'go get'

- grpc_server/gdalprocess/warp.go
- processor/tile_merger.go
Fixes:
```
tile_merger.go:14:7: don't use ALL_CAPS in Go names; use CamelCase
tile_merger.go:15:7: don't use ALL_CAPS in Go names; use CamelCase
tile_merger.go:16:7: don't use ALL_CAPS in Go names; use CamelCase
warp.go:45:7: don't use ALL_CAPS in Go names; use CamelCase
warp.go:46:7: don't use ALL_CAPS in Go names; use CamelCase
warp.go:47:7: don't use ALL_CAPS in Go names; use CamelCase
```
> Fix more 'go lint' warnings

- utils/config.go
- utils/empty_tile.go
- utils/output_encoders.go
- utils/palette.go
- utils/wcs.go
Cleaning `golint` warnings in the v0.6 branch. Please review @edisonguo.
> Fix golint warnings in new v0.6 code

- Makefile.in
It's customary for Autoconfiscated projects to have a `distclean` target that does more than `clean`, such as deleting the files `config.log`, `config.status` and the generated `Makefile`. This patch adds such a target for convenience.
> Add 'distclean' make target

- Makefile.in
Update `LDFLAGS` in the `Makefile`. Now that we are not using relative paths, the import paths for `utils.EtcDir` and friends need to be updated.
> Makefile: Update LDFLAGS

- templates/WMS_GetCapabilities.tpl
@bje- I added current="True" attribute to WMS GetCaps. This fixed https://github.com/nci/gsky/issues/16. A side note: we don't have to add code to explicitly handle time=current in the GetMap operation because time=current will fail http parameter validation https://github.com/nci/gsky/blob/master/utils/wms.go#L49 which leaves params["time"] unset. If params["time"] is unset, GSKY will use the latest time https://github.com/nci/gsky/blob/master/ows.go#L153 which conforms with the standard. Please review and merge the changes.
> added current="True" attribute to WMS GetCaps

- templates/WCS_DescribeCoverage.tpl
@bje- I changed crs from OGC to EPSG in WCS DescribeCoverage. This fixed https://github.com/nci/gsky/issues/17 Please review and merge the changes.
> changed crs from OGC to EPSG in WCS DescribeCoverage

- Makefile.in
Older versions of `gcc` do not default to C99. The `concurrent.c` code uses C99 features, so we need to pass `-std=c99`.
> Makefile fix: pass -std=c99 to gcc

- Makefile.in
There are two preparatory changes here:
*  Set a Make variable `$(GOBIN)` by running `go path GOBIN` and, if that is empty, runs `go path GOPATH` and appends `/bin`.
* Renames `$(PKGROOT)` to `$(BASEPATH)` for clarity.
> Makefile tweaks

- Makefile.in
Sean's `concurrent` is a user program and so should be installed in the `bin` directory.
> Install 'concurrent' in bin not sbin

- utils/config.go
@bje- I added infinite loop to wait for config file changes. Without this infinite loop, the goroutine exits the first time you run kill -1 <ows process id>.
> added infinite loop to wait for config file changes

- processor/tile_merger.go
@bje- As discussed with @monkeybutter ,the original timestamp sorting order on line 195 of tile_merger.go was in ascending order and this causes the block of if statement on line 44 never being executed. In addition, it is more reasonable to fill the missing pixels using the image data as latest as as possible. Therefore, it makes more sense to change the sorting order into descending order.
> changed timestamp sorting into decsending order

- .travis.yml
- Makefile.in
- grpc_server/gdalservice/pool.go
- ows_test.go
- utils/config.go
This patch introduces a trivial testsuite and the `Makefile` changes for `make check` (or `make test`). We can then activate Go testing in Travis CI.
The change also modifies the built-in paths to "." so that GSKY can be run from the source tree, not requiring `make install`.
> Add support for Go testing

- acceptance_tests/accept.go
- crawl/crawl.go
- grpc-server/main.go
- mas/api/api.go
- ows.go
- processor/drill_indexer.go
- processor/drill_merger.go
- processor/drill_types.go
- processor/palette.go
- processor/tile_grpc.go
- processor/tile_internal_pipeline.go
- processor/tile_merger.go
- processor/tile_pipeline.go
- processor/tile_proc_packed.go
- processor/tile_types.go
- utils/wps.go
- worker/gdalprocess/drill.go
- worker/gdalprocess/warp.go
- worker/gdalservice/process.go
This patch is the result of running `goimports -w` over the GSKY tree.
> Clean up Go imports

- .travis.yml
This adds in most (or all) of the required dependencies for GDAL (via Travis CI's support for easily installing packages inside the Docker image).
> Travis CI: Install more GDAL dependencies (libhdf5, etc)

- Makefile.in
This change backports the `go test` fix to the `v1.0` branch.
> [v1.0] Makefile.in: Test packages in the current directory and subdirectories

- Makefile.in
This change ensures that `go test` recurses into package subdirectories, testing everything.
> Test packages in the current directory and subdirectories

- ows.go
- utils/wcs.go
@bje- I made wcs version parameter optional. This fixed the WCS part of https://github.com/nci/gsky/issues/6 Please review and merge the changes.
> made wcs version parameter optional

- Makefile.in
- configure
- configure.ac
- crawl/extractor/info.go
- gdal-process/main.go
- utils/output_encoders.go
- utils/wps.go
- worker/gdalprocess/drill.go
- worker/gdalprocess/info.go
- worker/gdalprocess/warp.go
Use the `#cgo pkg-config` directive in the `.go` files to find compiler and linker flags when building -- no need to pass these on the command line any longer. Have every make target depend on a phony target that runs `pkg-config --exists gdal` to check for the module before running `go`.
Remove `--with-gdal` option from the `configure` script.
> Simplify build using pkg-config

- Makefile.in
- configure
- configure.ac
- crawl/extractor/info.go
- gdal-process/main.go
- utils/output_encoders.go
- utils/wps.go
- worker/gdalprocess/drill.go
- worker/gdalprocess/info.go
- worker/gdalprocess/warp.go
Use the `#cgo pkg-config` directive in the `.go` files to find compiler and linker flags when building -- no need to pass these on the command line any longer. Have every make target depend on a phony target that runs `pkg-config --exists gdal` to check for the module before running `go`.
Remove `--with-gdal` option from the `configure` script.
@monkeybutter, you may be interested in how this was ultimately done.
> [v1.0] Simplify build using pkg-config

- ows.go
- processor/tile_grpc.go
- processor/tile_internal_pipeline.go
- processor/tile_pipeline.go
- processor/tile_proc_packed.go
- utils/config.go
@bje- I made grpc recv message size configurable. The default value of gRPC library is 4mb which is too small for analytical operations over a large region such as running WCS over the whole Australia. This fixed https://github.com/nci/gsky/issues/74
> made grpc recv message size configurable

- .travis.yml
- Makefile.in
- testsuite/api.bats
- testsuite/crawl.bats
- testsuite/gdal-process.bats
Start off using Bats (https://github.com/sstephenson/bats). New tests can now easily be added to the `testsuite/` directory and will ultimately be run by Travis CI. It can be run by hand for now using `make check`.
> Start off using Bats with a new integration testsuite

- .travis.yml
This patch enables Travis CI `cache` support and caches `$HOME/local`, where we install all of the prerequisites built from source. In the `install` stage, we now check for one magic file, `$HOME/local/lib/libgdal.a`. The prerequisites are only built if this file is not present.  The build is **significantly** faster!
> Travis CI: cache $HOME/local tree

- utils/output_encoders.go
@bje- I added support for compressing wcs outputs. This fixes https://github.com/nci/gsky/issues/90. A few benchmarks using the following wcs request:
`
http://<gsky server>/ows/geoglam?SERVICE=WCS&service=WCS&crs=EPSG:4326&format=GeoTIFF&request=GetCoverage&height=<height>&width=<width>&version=1.0.0&bbox=-179,-80,180,80&coverage=global:c6:monthly_frac_cover&time=2018-03-01T00:00:00.000Z
`
```
height x width     with compression     no compression (baseline)
500x1000           262kb                       1.4MB
4000x4000          7.6MB                       46MB
8000x8000          65MB                        183MB
```
The compression ratio is good. Plus I also observed virtually no loss of speed.
> added support for compressing wcs outputs

- crawl/extractor/info.go
@bje- By default, gdalinfo automatically saves an auxiliary xml file under the same folder of the data file. This is problematic for us as the data files are owned by someone else. For example, I got this warning for crawling geoglam data: Warning 1: Unable to save auxiliary information in /g/data2/u39/public/prep/modis-fc/v310/tiles/8-day/cover/FC.v310.MCD43A4.h29v12.2017.006.nc.aux.xml. This PR fixes this.
> disabled xml auxiliary file creation in crawler

- .travis.yml
This change allows users to easily see in the Travis CI logs why the subsequent test for zero `gofmt` output may have failed.
> Run 'gofmt -d' without capturing the output for manual inspection

- testsuite/api.bats
- testsuite/crawl.bats
Bash regexps should not be quoted. These changes remove the quotes and the escape any spaces.
> Fix regexps in test cases

- processor/tile_grpc.go
Suggest running this from `.git/hooks/pre-commit`:
```
#!/bin/bash
for pkg in ./crawl ./utils ./processor ./worker/gdalservice ./worker/gdalprocess ; do
golint $pkg | grep -v -e unexported -e _GDAL
done
goimports -d .
exit 0
```
> Fix golint warnings in tile_grpc.go

- testsuite/wget.bats
This PR adds a test case that starts `gsky` on the local system and fires `wget` requests at it, looking for expected output. The first `@test` will make it clear how it works using bash regular expressions. Please consider using this for regression testing and for testing new features, as much as possible.
> Add a test that runs wgets and looks for expected output

- ows.go
- testsuite/wget.bats
This fixes https://github.com/nci/gsky/issues/130. 
@bje- Can you also please delete this branch: https://github.com/nci/gsky/tree/ows_trailing_slash ? I created it by mistake. I was supposed to create this bug fix branch under my own repo.
> fixed ows trailing slash issue

- Makefile.in
- crawl/crawl_pipeline.sh
@bje- This PR fixes the executable names of crawler to be consistent with the build script. It also copies crawl_pipeline.sh into the bin directory.
> Fix crawler build

- mas/api/mas.sql
@bje- There was syntax error in mas/api/mas.sql due to my careless-ness. This PR fixes it.
> fixed mas api sql syntax error

- Makefile.in
- ows.go
- processor/tile_jpg_enc.go
- processor/tile_png_enc.go
@bje- Today when I was trying to build a docker image for gsky using ./configure and make instead of the ansible scripts we internally used, I found there are a few places in the codebase that are not consistent with the Makefile script. This PR fixes them.
> Fix build codebase inconsistencies

- Makefile.in
@bje- the png files need to be under `$dataroot/gsky` like `templates/` and `static/`. Chris needs this fix urgently. So i'll go ahead to merge this PR.
> install png files into dataroot/gsky

- Makefile.in
- ows.go
@bje- The png files need to be installed to `$(datarootdir)/gsky` like `templates/` and `static/`. Chris needs this urgently. So I'll go ahead to merge this PR.
>  install png files to datarootdir/gsky

- ows.go
@bje- It's quite often that the clients (e.g. terriajs) has a proxy server like varnish in front of gsky endpoint. The problem is that once we updated the timestamps in GetCaps, the proxy server still caches the old reponse for at least 24 hours. We will need to instruct the proxy server not to cache GetCaps response.
> added no-cache for getCaps

- utils/api_test.go
- utils/config.go
@bje- I added check against some zero timestamp steps. If we don't have these checks, zero steps will cause infinite loop. Also, some timestamp steps can be zero as they're not used.
> added check against some zero timestamp steps to prevent infinite loop

- utils/config.go
@bje- The template engine used by the config facility struggles with relative path when loading the config files. So I expand the relative paths to absolute paths in order to fix this problem.
> fixed config template path issue

- crawl/extractor/ruleset.go
@bje- I added support for crawling the Sentinel 2 Ard dataset. This is required by GA.
> added support for crawling sentinel 2 ard

- crawl/extractor/ruleset.go
@bje- It turns out that the namespaces in the sentinel2 datasets are not stored in the data files. So we have to parse the filenames to extract those using RegEx.
> added support for parsing sentinel2 namespaces

- ows.go
- templates/WCS_DescribeCoverage.tpl
- utils/config.go
https://github.com/nci/gsky/pull/204 introduced a regression bug that results in incorrect MAS query returning wrong timestamps. This PR fixes this problem.
> fixed auto mas timestamp issues

- ows.go
- templates/WCS_DescribeCoverage.tpl
- utils/config.go
#204 introduced a regression bug that results in incorrect MAS query returning wrong timestamps. This PR fixes this problem.
> fixed auto mas timestamp issues (#209)

- mas/api/api.go
- mas/api/mas.sql
- mas/db/shard.sql
- mas/db/shard_create.sh
- ows.go
- utils/config.go
Added support for a token-based approach to automatically refresh timestamps from MAS. During the GSKY startup, GSKY will pull MAS for timestamps and MAS will also return a token to GSKY. If GSKY presents this token to MAS for subsequent timestamp queries, MAS will return empty timestamps assuming that GSKY caches the timestamps. If GSKY doesn't present the token to MAS, MAS will return the full range of timestamps. In short, this approach enables lazy refresh of MAS timestamps.
> Token timestamp cache

- utils/config.go
If the MAS shard has no data and a MAS timestamps query comes in, a token will be generated to reflect the current empty state of the shard. This token will also need to be saved in GSKY config code.
> fixed a corner case for saving MAS token when MAS shard is empty

- ows.go
- utils/output_encoders.go
Despite the fact that GSKY deletes the temporal raster files after the completion of WCS request, the disk space allocated to those temporal files are not releases because there are open file descriptors reference these files. These open file descriptors come from calling GDALOpen() to create the temporal files. If WCS returns prematurely due to processing error, these open file descriptors will not be closed which results in GDAL file descriptor leakage. This PR  "defers" GDALClose() to ensure the file descriptors closed whenever WCS returns.
> fixed WCS file descriptor leak

- crawl/crawl.go
- crawl/extractor/info_sentinel2_yaml.go
- crawl/extractor/types.go
Added support for extracting Sentinel 2 metadata by crawling its yaml files instead of the raw files. We experience several order of magnitude speedup.
> crawl Sentinel2 yaml files

- ows.go
- processor/feature_info.go
- templates/WMS_GetCapabilities.tpl
- utils/config.go
- utils/wcs.go
- utils/wms.go
The OGC WMS standard supports defining one or more "styles" in a layer which allows different views of the same layer (eg. false and true colour). Currently GSKY only supports a flat namespace of layer definitions without styles so we have to emulate this by generating a layer for every possible layer and style combination. While we have reduced the amount of repetition required for the catalog generation, this doesn't solve the following client side issues:
* Users are presented with a confusingly long list of layers where most of them are variants of the same layer.
* The payload size of GetCapabilities is much larger than it needs to be because lots of attributes (eg. timestamp list) have to be repeated in each layer definition.
* The NationalMap/TerriaJS UI allows users to easily …
> Added support for WMS styles

- ows.go
- processor/feature_info.go
- processor/tile_grpc.go
- processor/tile_pipeline.go
- utils/config.go
Currently GSKY tries to limit memory usage by comparing how much it thinks it will need for a given request vs. how much system memory is left at that time. This approach has an in-built race condition and often the OOM killer is triggered anyway. So after discussion we decided that we'll change this test to instead compare the predicted maximum request memory usage against a global limit set in the configuration. Any request (whether WCS or WMS) exceeding that limit will be rejected. The intention here is solely to prevent requests that are considered to be unacceptably large.
> added configurable max grpc buffer size

- utils/wms.go
The WMS GetLegendGraphics operation sometimes use the singular version of the layers parameter (i.e. layer vs layers). Currently GSKY only supports layers instead of layer. Thus we need to support both of them to cater for GetLegendGraphics from the clients who use the singular version.
> added support for singular layer

- ows.go
- processor/drill_merger.go
- processor/feature_info.go
- processor/tile_grpc.go
- processor/tile_merger.go
- processor/tile_pipeline.go
- processor/tile_types.go
- utils/config.go
added support for evaluating arbitrary band maths expressions on the fly. The band maths facility has the following features:
* It does not pose any security risks as the expressions cannot access any IO or system libraries.
* The expressions are evaluated by a light-weight interpreter written in golang which does not require setting up any external code execution environment.
* The arithmetics support element-wise vector operations as well as broadcasting operations between scalars and vectors.
Known limitations:
* Apparently we do not have any built-in maths functions. But we can easily add maths functions when we need them.
> added support for band maths

- ows.go
- utils/config.go
A WPS input element with empty MinOccurs causes crash for owslib. This is because owslib will try to parse MinOccurs as long as its set even though its value is an empty string. To fix this, we default MinOccurs to 0 instead of an empty string.
> fixed empty minoccurs for wps inputs

- ows.go
- utils/config.go
The memory consumption and performance of WCS comes from a trade-off between size of the splitted tiles (e.g. 1024x1024) and the number of underlying data files associated with the bounding box. the complexity is that there is no magic formulae to determine the size of the splitted tiles including not splitting at all. In the extreme case, let's say there is only one data file for the bounding box (this is possible for climate datasets), then we can afford processing the large-sized tile at once and will be certainly faster than splitting it. In contrast, if we have a lot of files, there is virtually no way we can process those files for big tile size without overwhelming the grpc backend. In this case, splitting it is a sensible way to do.  Thus the splitting size including no splitting …
> made wcs tile size configurable

- ows.go
- utils/config.go
- utils/empty_tile.go
More often than not, users overlay layers from other data sources on top of the layers served by GSKY to create a synthetic WMS layer for analysis. Apparently GSKY returns a "data unavailable" image for the region with missing data. This gives poor visual experience for the overlaid layers. Thus it makes more sense if we return a transparent image for missing data in this scenario. Having said that, we should still maintain the functionality to return the "data unavailable" image via a configuration entry when the user needs to indicate the region with missing data.
> made data unavailable legend image transparent by default

- ows.go
- processor/feature_info.go
defaulted to latest timestamp if time parameter is empty for getFeatureInfo. This is to be consistent with GetMap
> defaulted to latest timestamp if time parameter is empty

- ows.go
Apparently GSKY returns 400 bad request if the style parameter is not set in the WCS request or not found in the configured style list. This is, however, too restrictive if the layer has no styles or a single style. In the case of no style or single style, we should default to the layer itself or the single style to make best efforts to return WCS results to the user.
> fixed single style issue

- mas/api/mas.sql
Previously the `mas_intersects()` function tries to project the requested bbox into EPSG:4326 before performing the polygon intersection. This approach is problematic because many coordinate systems cannot be perfectly projected into 4326. The reason for the projection failure is due to the fact that 4326 has mathematical issues in handling north and south poles. In fact, it is unnecessary to project the requested polygon to 4326 before the intersection since `mas_intersect_polygons()` always projects the requested polygon into the coordinate system of the dataset before intersection. (i.e. https://github.com/edisonguo/gsky-1/blob/mas_intersects_fix/mas/api/mas.sql#L294)
An example of the failure and the fixed can be illustrated in the following screenshots. The top is the original …
> removed unecessary projection to epsg:4326

- mas/api/mas.sql
It turns out that PostGIS st_simplify can result in invalid geometry. It is thus essentially to preserve the topology while simplifying geometry.
> preserving topology while simplifiying polygon

- worker/gdalprocess/drill.go
If a large polygon contains a small polygon inside of it (say a polygon that bounds a large region while there is another polygon that bounds a small lake inside of this region), `OGR_G_Intersects()` gives error complaining that topology exception due to self-intersecting polygon, which in fact it is not. To work around this problem, we will have to clean up the polygon before calling `OGR_G_Intersects()`. In words, we call `OGR_G_Buffer(original_polygon, 0.0)` to remove vertices whose distances are almost zero (aka. self-intersecting).
> fixed self-intersecting polygon issue

- ows.go
- processor/feature_info.go
- processor/tile_merger.go
- processor/tile_pipeline.go
- utils/config.go
This PR contains initial implementation of blended services. The features implemented in this PR as as follows:
* The outputs of arbitrary number of layers can be merged (i.e. blended) in a best-of-last-pixel fashion. Early stopping is also implemented to prune unnecessary IOs. For example, supposed we have 4 layers participating the blending service. If all the pixels become valid after blending the 2nd layer, there is no point to continue blending the 3rd and the 4th layer but early stop the blending process.
* The timestamps of the participating layers form a union ordered set for WMS `GetCapabilities`.
* `getFeatureInfo` can now return the union ordered set of timestamps of all the participating layers associated with the point of interest. This is to facilitate point drill over time.
> initial implementation of blended services

- worker/gdalprocess/drill.go
If the input to WPS is a single point, `OGR_G_Buffer` will mistakenly eliminate this single point because the distance of the single point is of course less than any possible threshold. To handle this scenario, we will check if the geometry is empty after `OGR_G_Buffer`. If it is empty, we will simply clone the original geometry.
> fixed point drill issue

- processor/tile_indexer.go
This PR adds support for skipping MAS query if `data_source` in the layer config is blank. This is useful because blended service is often configured with blank `data_source` for the layer in question.
> skip mas query if data_source is blank

- processor/feature_info.go
This PR removes the duplicated check for blank `data_source` in `getFeatureInfo`. This check causes trouble for blended layer since blended layer is likely to always configure blank `data_source`.
> removed duplicated check for blank data source in getFeatureInfo

- crawl/extractor/info.go
- crawl/extractor/ruleset.go
This PR adds support for default timestamps. This is useful for those datasets that do not have timestamps. In this case, we will have hard wire some default timestamps for MAS time query to work.
> added support for default timestamps

- crawl/extractor/info.go
- crawl/extractor/ruleset.go
This PR adds support for user-defined axes. This is useful when mapping linearised GDAL bands to axes. For example, some GeoTIff files use band 1, 2, 3 to represent red, green and blue. GSKY, however, requires three distinct variables for RGB. With this PR, we can now map create a pseudo axis (say colour) to map band 1, 2, 3 to the colour axis.
> added support for user-defined axes

- ows.go
- utils/wms.go
This PR adds support for dynamic colour scale range. This feature is useful for those who wants to tweak the colour scales (i.e. `offset` and `clip`) on the fly on a per region basis instead of a global setting applied across regions.
> added support for dynamic colour scale range

- ows.go
- processor/tile_types.go
- utils/config.go
- utils/raster_scaler.go
- utils/wms.go
This PR adds support for rendering WMS images in logarithmic scale. This feature is essential for rendering data with different orders of magnitude. e.g. magnetotelluric conductivity models
> added support for rendering wms images in logarithmic scale

- crawl/extractor/info.go
- crawl/extractor/ruleset.go
This PR adds support for targeting netCDF metadata. This is useful for VRT XML derived from netCDF files.
> added support for targeting netCDF metadata

- crawl/crawl_pipeline.sh
This PR adds support for generic crawler via setting the `CRAWL_BIN` environment variable. This feature is useful for crawlers other than the default `gsky-crawl` utility, as long as the json outputs of the crawler are MAS compatible.
> added support for generic crawler

- crawl/crawl_pipeline.sh
This PR adds support for crawl (aka. `gdal_json()`) to stop on error to prevent emiting garbage gdal json.
> Crawl stops on error

- ows.go
- utils/config.go
This PR adds support for loading timestamps on demand. For datasets such as the climate ones with large volume of timestamps, it is not possible to pre-load all the timestamps and cache them in memory during GSKY startup. Therefore, we only load the timestamps when GetCapabilities is called and discard the timestamps after the call returns.
> Timestamps on demand

- utils/config.go
This PR fixes `TimestampsToken` passing for on-demand timestamps loading.
> fixed on-demand timestamps token

- crawl/crawl.go
This PR adds a check for the `nc_metadata` command line switch for the crawler.
> added nc_metadata check

- worker/gdalprocess/warp.go
This PR add `GDAL_OF_RASTER` to disable netCDF vector fields warnings.
> added GDAL_OF_RASTER to disable netcdf vector fields warnings

- processor/tile_indexer.go
This PR adds epsilon-based comparison for dimension endpoints to avoid small rounding errors.
> added epsilon-based comparison for dimension endpoints

- ows.go
- processor/feature_info.go
- processor/tile_pipeline.go
- utils/wms.go
This PR disables overview extrapolation for WCS by default
> disable overview extrapolation for wcs by default

- processor/tile_pipeline.go
This PR fixes empty blended namespace for `tile_pipeline`.
> fixed empty blended namespace for tile_pipeline

- utils/gdal_init.go
This PR disables GDAL `readdir()` on `open()` for performance.
> disabled gdal readdir on open

- processor/tile_pipeline.go
This PR fixes empty_tile for unnamed expressions in `getFeatureInfo`. `geoReq.BandExpr.Expressions` is `nil` if the expressions are unnamed.
> fixed empty_tile for unnamed expressions in getFeatureInfo

- processor/feature_info.go
- processor/tile_indexer.go
As we do not assume timezones when dealing with the timestamps, converting from unix timestamps into golang datetimes must be done without timezones. Otherwise the original and the converted timestamps will not be consistent.
> properly handled timezones when converting from unix into golang timestamps

- grpc-server/main.go
This PR adds support for non-blocking response channel for worker processes. Non-blocking response channel improves concurrency of the worker processes.
> added non-blocking resp channel for worker processes

- ows.go
- utils/ogc_encoders.go
This PR properly initialises WCS temp file when the first tile is empty. Previously WCS initialises the number of bands of the temp file against the first tile. This is inadequate if the first tile happens to be an empty tile with a single band while one of subsequent tiles is non-empty with arbitrary number of bands.
> properly initialising wcs temp file when the first tile is empty

- metrics/metrics.go
- ows.go
This PR support for filtering out unwanted URL parameters for metrics logging. This is essential to prevent large URLs to flood the metrics logs.
> added support for filtering out unwanted URL parameters for metrics logging

- utils/config.go
This PR made verbose optional to a few config logs. This is to prevent log flooding at the presence of large number of namespaces.
> made verbose optional to config logs

- processor/tile_pipeline.go
This PR adds guard against raster type casting. The guards as such are needed because empty tiles are always set to `ByteRaster` while the non-empty tiles can be of any type.
> added guard against raster type casting

- processor/tile_grpc.go
- processor/tile_merger.go
- processor/tile_pipeline.go
This PR removes grouping RPC calls by polygon. Grouping RPC by polygon only works assuming no intersection among polygons. This assumption is broken for a few datasets.
> removed grouping rpc by polygon

- utils/config.go
This PR fixes empty namespace issue in fusion colour palattes.
> fixed empty namespace issue in fusion colour palattes

- processor/feature_info.go
- templates/WMS_GetCapabilities.tpl
- utils/config.go
- utils/wms.go
This PR adds support for pseudo-style as a service. This feature, for example, enables attaching delta style as a service to the corresponding underlying style.
> added support for pseudo-style as a service

- utils/config.go
This PR set default input layer name to the name of the current layer if input layer name is empty.
> set default input layer name if empty

- crawl/crawl.go
- crawl/crawl_pipeline.sh
This PR adds support for batch crawler. Batch crawler significantly improves crawling performance by reducing the overhead of launching the `gsky-crawl` process repetitively.
> added support for batch crawler

- grpc-server/main.go
- worker/gdalprocess/pool.go
- worker/gdalprocess/process.go
This PR adds support for automatically restarting `gdal-process` once the maximum number of tasks are processed. The reason is that several third-party drivers shipped with `gdal` have memory leak issues. The safest way to prevent a potential OOM is to restart the `gdal-process`.
> restarting gdal-process once max tasks processed

- mas/db/shard_refresh.sh
This PR prunes `refresh_views()` to improve ingestion performance. Users can perform ad-hoc `refresh_views()` when needed.
> pruning refreshing views

- mas/db/shard.sql
This PR changes to use logged tables for `path` and `metadata`. Ingestion benchmark shows little performance loss when using logged tables for `path` and `metadata`.
> changed to use logged tables

- processor/tile_grpc.go
- processor/tile_indexer.go
This PR adds support for interleaving the processing between `tile_indexer` and `tile_grpc`. Essentially  gRPC doesn't have to wait for the complete results from the indexer but kick start as soon as partial results are available.
> interleave processing between indexer and grpc

- mas/api/mas.sql
This PR adds a global limit on the result from the `mas_intersects` SQL. This further speeds up the limit query.
> added global limit on the result from mas_intersects SQL

- processor/tile_grpc.go
This PR adds guards against non-positive values for grpc_tile_size.
> added guards against non-positive values for grpc_tile_size

- ows.go
This PR globally disables cache in HTTP response. For near-time services, responding data can frequently change. It is essentially to disable front-end cache to ensure data up-to-date.
> added global cache control for http response

- mas/db/shard.sql
This PR disables creation of public views. This is to facilitate parallel ingestion of data from different shards. One can always create the public views manually if needed.
> disabled creation of public views

- mas/api/mas.sql
This PR provides a workaround to an issue in `project_create()` since PROJ 6.0.0+. Essentially with PostGIS 3.0.0+ built against PROJ 6.0.0+, if the `srid` is custom instead of built-in `srid` registered in the `spatial_ref_sys` table, `ST_Transform()` with the `srid` integer argument will output `project_create: crs not found` error.
> worked around crs not found for proj_create() since proj 6.0.0

- gdal-process/main.go
This PR adds support for timing out the worker gdal-processes. This is to address https://github.com/nci/gsky/issues/378
> added support for worker timeout

- crawl/crawl_pipeline.sh
This PR fixes unbounded variable issue in `crawl_pipeline.sh`
> fixed unbounded variable issue

- grpc-server/main.go
- worker/gdalprocess/oom_monitor.go
This PR adds support for monitoring the memory consumption of the worker processes. An OOM may be triggered to terminate the worker process with largest residential virtual memory if the system `availableMemory` is below a threshold.
> added support for OOM monitor of the worker processes

- ows.go
- processor/date_splitter.go
- processor/drill_indexer.go
- processor/drill_types.go
- templates/WPS_VRTs/masks_example.vrt
- utils/config.go
This PR adds support for rescaling `rasterXSize` and `rasterYSize`. This is useful when computing WPS statistics in downsampled images.
> added support for rescaling raster size

- ows.go
- processor/drill_merger.go
This PR replaces string concatenation with `strings.Builder` in CSV construction of the WPS pipeline. This improves speed and memory efficiency in string manipulation.
> replaced string concat with strings.Builder for efficiency

- templates/WPS_Outputs/geometryDrill/landsat3_ndvi.tpl
- templates/WPS_Outputs/geometryDrill/landsat3_ndwi.tpl
- templates/WPS_Outputs/geometryDrill/sentinel2_ndci.tpl
- templates/WPS_Outputs/geometryDrill/sentinel2_ndvi.tpl
- templates/WPS_Outputs/geometryDrill/sentinel2_ndwi.tpl
This PR removes yAxisMin/Max for WPS output templates as they are not necessary for the final rendering of the plots.
> removed yAxisMin/Max for WPS output templates

- utils/wms.go
This PR fixes project skewness issue in WMS. The root cause of this issue was unintended modification of the input values of `geoReq.BBox`.
> fixed projection skewness issue in WMS

- mas/api/mas.sql
This PR queries `auth_srid` instead of `srid` for `proj4text` from `spatial_ref_sys`. This is because `srid` and `auth_srid` do not always have correspondence.
> query auth_srid instead of srid for proj4text from spatial_ref_sys

- mas/api/mas.sql
- mas/db/ingest.sh
- mas/db/ingest_pipeline.sh
- mas/db/schema.sql
- mas/db/shard.sql
- mas/db/shard_refresh.sh
This PR adds support for incremental updates on MAS shards. Previously ingesting crawl results into MAS requires a refresh of materialised views, which is expensive for large datasets. This PR replaces the materialised views by tables, which enables incremental updates on them.
> added support for incremental updates on MAS shards

- mas/api/mas.sql
- mas/db/shard.sql
This PR makes timestamps query token consistent across queries and nodes. This is important for MAS with load balancer.
> consistent token for querying timestamps cache

- processor/drill_merger.go
This PR does not treat empty input to drill_merge an error.
> not treating empty input to drill_merge an error

- templates/WPS_VRTs/masks_example.vrt
This PR takes nodata into account for mask bands in the VRT example.
> taking nodata into account for mask bands

- dap.go
- metrics/metrics.go
- processor/drill_indexer.go
- processor/feature_info.go
- processor/tile_extent.go
- processor/tile_grpc.go
- processor/tile_indexer.go
- utils/config.go
- utils/dap4_ce_parser.go
- utils/dap4_encoders.go
- utils/url_parser.go
- utils/wms.go
This PR makes use of empty struct for key-only hash map lookup. This reduces memory footprint of these hash maps.
> made use of empty struct for key-only hash map lookup

- crawl/extractor/types.go
This PR names file id properly for the POSIX crawler.
> properly naming file id for posix crawler

- crawl/extractor/info_posix.go
This PR optimises `readdir()` for the POSIX crawler by eliminating unnecessary `lstat()`.
> optimised readdir() for posix crawler

- libs/gdal/frmts/gsky_netcdf/netcdfdataset.cpp
This PR suppressed latitude uneven spacing warning in the netCDF driver.
> suppressed latitude uneven spacing warning

- libs/gdal/frmts/gsky_netcdf/netcdfdataset.cpp
This PR adds adaptive netCDF cache size. This is essential to datasets with netCDF files using non-uniform chunk sizes.
> adaptive netcdf cache size

- libs/gdal/frmts/gsky_netcdf/netcdfdataset.cpp
This PR suppresses 1D variable warnings for unindexed dimensions.
> suppress 1D variable warnings

- libs/gdal/frmts/gsky_netcdf/netcdfdataset.cpp
This PR suppresses 1-pixel width/height warning for netCDF variables.
> suppressed 1-pixel width/height warning

- mas/api/mas.sql
This PR adds lock timeout on the PostgreSQL objects in the shard corresponding to the dataset during bulk ingestion.
> added lock timeout

- utils/config.go
This PR makes timestamps error more informative when loading layer configs.
> made timestamps error more informative

- docker/Dockerfile
This PR makes to use Ubuntu LTS base image for GSKY docker build.
> made to use Ubuntu LTS base image

- mas/db/shard_ingest.sh
This PR enables configurable concurrent limit and batch size of `shard_ingest`.
> configurable shard_ingest

- utils/config.go
This PR fixes namespace if `config.json` is directly referenced instead of its containing directory.
> fixed namespace for config.json

- ows.go
This PR returns error for invalid palette requested from the `colorscheme` parameter.
> returning error for invalid palette

- mas/api/api.go
- mas/api/mas.sql
- ows.go
- templates/catalogue_index.tpl
- templates/gsky_layers.tpl
- templates/terria_catalog.tpl
- utils/catalogues.go
- utils/config.go
This PR adds support for auto-catalogues. Auto-catalogues derives catalogue information from MAS given the `gpath` structure for each shard. With the derived catalogue information, it then constructs layer configs on-the-fly. This feature enables fast prototyping of new datasets. By default, this feature is turned off. To enable this feature, the following steps are required:
* Add `enable_auto_layers: true` to the root config file. The root config file is the config file under the config root directory specified by `-conf_dir`
```
{
"service_config": {
"enable_auto_layers": true,
....
},
....
}
```
* If `static/catalogues` directory exists, the `index.html` files override the the on-the-fly auto-catalogues. These files need to be removed.
> added support for auto-catalogues

- utils/config.go
This PR disables on-demand timestamps loading by default. On-demand timestamps loading is not compatible with blended layers.
> disabled on-demand timestamps loading by default

- mas/api/mas.sql
This PR drops SQL functions before creating them. This is required when the new and old functions have different signatures.
> drop before creating SQL functions

- ows.go
This PR raises error for empty configs generated from MAS.
> raised error for empty configs generated from MAS

- mas/api/api.go
- mas/api/mas.sql
- mas/db/shard.sql
- mas/db/shard_create.sh
- mas/db/shard_reset.sh
- ows.go
- utils/config.go
- utils/ows_cache.go
This PR adds ows_cache for caching the data computed for WMS GetCapabilities. This is to improve the response time for WMS GetCapabilities for layers with large number of timestamps.
> added ows_cache for WMS GetCaps

- ows.go
- utils/config.go
This PR fixes on-demand timestamps for a single namespace.
> fixed on-demand timestamps for a single namespace

- ows.go
- utils/config.go
- utils/runtime_file_resolver.go
This PR adds support for resolving runtime data files from a list of search paths. The `-data_dir` CLI argument takes a `:` separated 
list of paths. In addition to the search path specified by `-data_dir`, the current working directory (CWD) and the directory of the `ows` executable are also appended to the search path.
> added support for resolving runtime data files from a list of search paths

- utils/config.go
This PR removes unnecessary config echos, which makes ows startup less verbose.
> removed unnecessary config echo

- worker/gdalprocess/warper.cxx
This PR reduces memory footprint for the warper. Now the memory consumption for GDAL read is at most one block of the data file.
> reduced memory footprint for the warper

- README.md
This PR migrates from travis-ci.org to travis-ci.com. travis-ci.org is shutting down around the end of May 2021.
> migrated to travis-ci.com

- libs/gdal/frmts/gsky_netcdf/netcdfdataset.cpp
This PR addes interpolation of  large 1D variables instead of loading all its values. The interpolation is specified by `-oo interp_1d_var=<max element threshold>`.
> added interpolation of 1D variables

- worker/gdalprocess/drill.go
This PR fixes GDAL axis order incompatibility documented here https://gdal.org/tutorials/osr_api_tut.html#crs-and-axis-order. This PR also addresses https://github.com/nci/gsky/issues/534.
> fixed GDAL axis order incompatibility

- worker/gdalprocess/warper.cxx
This PR fixes integer overflow issues in the warp operation. Integer overflow occurs when the source image has size greater than 2GB.
> fixed warp integer overflow

- templates/WMS_GetCapabilities.tpl
This PR makes the time parameter mandatory in WMS GetCapabilities.
> made time parameter mandatory in WMS GetCaps
