mas/api/api.go
mas/api/mas.sql
mas/db/schema.sql
mas/db/shard.sql

Start the process of extracting MAS from NCI. There's a bunch more that could be done, but this removes some immediate blockers for use with GSKY outside NCI.

GDATA and PDAL fixes

---

mas/db/shard_exists.sh

This script is not really needed. Less is more.

Remove shard_exists.sh

---

Makefile.in
mas/db/schema.sql
mas/db/shard_exists.sh

Some of the MAS scripts rely on Sean Pringle's `concurrent` program. Build and install it as part of the GSKY build.

Build concurrent

---

acceptance_tests/accept.go
grpc_server/gdalprocess/drill.go
grpc_server/gdalprocess/info.go
grpc_server/gdalprocess/warp.go
grpc_server/gdalservice/pool.go
mas/api/api.go
ows.go
processor/drill_indexer.go
processor/palette.go
processor/tile_indexer.go
processor/tile_merger.go
utils/config.go
utils/wms.go
utils/wps.go

This is the first handful of changes from running `golint`. I'd like to submit and have them reviewed in batches.

Initial run of 'golint'

---

templates/WMS_GetCapabilities.tpl

@bje- I removed the non-standard csr codes suggested here: https://github.com/nci/gsky/issues/11 Please review and merge the changes.

removed non-standard crs codes

---

processor/tile_merger.go
utils/config.go

@bje- I added support for bitwise testing for cloud masking. Please review and merge.

added support for bitwise testing for cloud masking

---

crawl/extractor/info.go
grpc_server/gdalprocess/info.go
grpc_server/gdalservice/pool.go
grpc_server/grpc_server.go
ows.go
processor/drill_grpc.go
processor/drill_merger.go
processor/info_crawler.go
processor/tile_grpc.go
processor/tile_indexer.go
processor/tile_png_enc.go
processor/tile_scaler.go
utils/config.go
utils/empty_tile.go
utils/output_encoders.go
utils/raster_scaler.go
utils/wms.go
utils/wps.go

There was quite a lot of commented out code, both inline and block comments. This removes most of them, but leaves behind things that look important.

Remove commented out code

---

templates/WMS_GetCapabilities.tpl

@bje- I added required xml fiels to WMS GetCaps for compliance reasons. This fixed https://github.com/nci/gsky/issues/8 Please review and merge the changes.

added required xml fiels to WMS GetCaps for compliance reasons

---

templates/WMS_GetCapabilities.tpl

@bje- I removed POST support for WMS GetCaps. This fixed https://github.com/nci/gsky/issues/9 Please review and merge.

removed POST support for WMS GetCaps

---

acceptance_tests/accept.go
crawl/crawl.go
grpc_server/gdal_process.go
grpc_server/gdalprocess/drill.go
grpc_server/gdalprocess/info.go
grpc_server/gdalservice/pool.go
grpc_server/grpc_server.go
grpc_server/test_warp_process.go
mas/api/api.go
ows.go
processor/drill_merger.go
processor/info_grpc.go
processor/tile_grpc.go
processor/tile_indexer.go
processor/tile_internal_pipeline.go
processor/tile_merger.go
processor/tile_proc_packed.go
utils/config.go
utils/output_encoders.go
utils/wcs.go

These edits were automatically made by `go fmt`.

Formatting fixes from "go fmt"

---

ows.go
utils/wms.go

@bje- I made version parameter optional in wms request. This fixed https://github.com/nci/gsky/issues/6 Please review and merge the changes.

made version parameter optional in wms request

---

.travis.yml

Next step for Travis CI: build GDAL as a dependency for GSKY.

Build GDAL 2.2.4

---

ows.go

@bje- I added utils.DataDir to WCS templates. Please review and merge the changes.

added utils.DataDir to WCS templates

---

testsuite/api.bats
testsuite/crawl.bats
testsuite/gdal-process.bats
testsuite/grpc-server.bats

Add more Bats tests

---

testsuite/gdal-process.bats
testsuite/grpc-server.bats

Add more Bats tests for gdal-process and grpc-server

---

ows.go
processor/tile_grpc.go
processor/tile_merger.go
processor/tile_pipeline.go
processor/tile_types.go
utils/config.go

@bje- This is the code for https://github.com/nci/gsky/issues/95

modified algorithms for the streaming tile processing model

---

ows.go
utils/output_encoders.go

@bje- These checks are meant to guard against a few corner cases our clients raised.

added checks against corner cases

---

mas/api/api.go

This should restore Travis CI.

go fmt fix

---

crawl/crawl.go
crawl/extractor/info.go

@bje- This fixes https://github.com/nci/gsky/issues/109. I md5sum checked the crawler output files before and after my code changes and they're identical.

added support for concurrent gdal IO and error outputs stderr to Gsky cralwer

---

templates/WPS_GetCapabilities.tpl

Update ows:IndividualName, ows:PositionName and ows:Phone

---

crawl/extractor/info.go

[v1.0] Check for NAN stats in crawler info

---

mas/api/mas.sql

@bje- This fixes https://github.com/nci/gsky/issues/114

made both time endpoints inclusive for time range overlaping

---

mas/api/mas.sql

back porting PR #115 into v1.0

back porting PR #115 into v1.0

---

mas/db/shard_create.sh
mas/db/shard_ingest.sh
mas/db/shard_refresh.sh
mas/db/shard_reset.sh

Remove runuser invocations

---

static/index.html

Clean-ups to the static `index.html` page.

Remove old material from index.html

---

mas/db/shard_create.sh

@bje-  This fixes https://github.com/nci/gsky/issues/120

added check for existence of shard schema

---

mas/api/api.go
mas/api/mas.sql
mas/db/shard_create.sh
utils/api_test.go
utils/config.go

@bje- This feature needs to be in v1.1 Currently the time existing timestamp generators have issues with geoglam monthly data.

pulling timestamps from mas for v1.1

---

crawl/README.md
crawl/crawl_pipeline.sh
mas/MAS_Design.md
mas/README.md
mas/db/ingest_pipeline.sh

@bje- I added pipeline scripts for crawler and mas ingestion to streamline the crawling and ingestion process. I also added documentation for crawler and mas. This fixes https://github.com/nci/gsky/issues/128.

Crawler mas ingestion pipelines

---

README.md
config_json.md
ows.go
static/index.html

@bje- This fixes https://github.com/nci/gsky/issues/132

Documentation updates

---

mas/api/mas.sql
utils/api_test.go
utils/config.go

@bje- This fixes https://github.com/nci/gsky/issues/137.

fixed mas timestamps bugs

---

utils/raster_scaler.go
utils/raster_scaler_test.go

@bje- This fixes https://github.com/nci/gsky/issues/135.

fixed raster scaling bugs

---

processor/drill_grpc.go

@bje- This fixed https://github.com/nci/gsky/issues/141. 
@juan-guerschman will be happy about this fix.

imporved drill grpc performance

---

mas/db/shard_create.sh

@bje- This fixes https://github.com/nci/gsky/issues/143

added guard against different gpath for same shard

---

mas/api/api.go
mas/api/mas.sql
ows.go
processor/drill_indexer.go
processor/drill_pipeline.go
utils/config.go

This fixes https://github.com/nci/gsky/issues/139.  A quick experiment for performance figures: 
The input is a polygon for the boundary of an Australian city with 56000+ points.
* Exact polygon intersection takes 1 minute and 36 seconds.
* The polygon simplification approach takes 26 seconds.

added support for simplifying complicated polygons

---

utils/api_test.go
utils/raster_scaler_test.go

This PR fixes a a few `golint` warnings that have crept in.

Fix golint warnings

---

Makefile.in
crawl/crawl_pipeline.sh
docker/Dockerfile
docker/README.md
docker/build_deps.sh
docker/build_gdal.sh
docker/build_gsky.sh
docker/build_pgsql.sh
docker/build_postgis.sh
docker/gsky_entry_point.sh
docker/ingest_sample_data.sh
docker/setup_mas.sh
docker/setup_terriajs.sh
docker/terria_config.json

@bje- This is the PR for https://github.com/nci/gsky/issues/152

Gsky docker image

---

mas/api/api.go

@bje- This is for https://github.com/nci/gsky/issues/156

Guarded against lazy evaluation of sql.Open()

---

crawl/extractor/info.go
crawl/extractor/types.go

@bje-  This is for https://github.com/nci/gsky/issues/161

added supported for capturing nodata values

---

ows.go
utils/config.go
utils/json_unmarshal_test.go

@bje- The changes in this PR essentially come from Chris's deployment feedbacks.

added configurable data/etc dir and options validating config files only

---

ows.go

@bje- this change needs to be in v1.0.

made data and etc dirs configurable from commandline

---

ows.go

@bje-  this is for https://github.com/nci/gsky/issues/169

changed into outputing error message directly rather than wps_exception.tpl

---

grpc-server/main.go
processor/drill_grpc.go
processor/tile_grpc.go
worker/gdalprocess/drill.go
worker/gdalprocess/process.go

@bje- This is for https://github.com/nci/gsky/issues/166

Worker bug fix

---

ows.go
templates/WCS_GetCapabilities.tpl
templates/WMS_DescribeLayer.tpl
templates/WMS_GetCapabilities.tpl
utils/api_test.go
utils/config.go

@bje-  this is for https://github.com/nci/gsky/issues/171

refresh dates for wms and wcs GetCaps

---

worker/gdalprocess/drill.go

@bje- I added guard for negative or zero bandStrides values.

added guard for negative or zero bandStrides values

---

docker/data_ingestion.md

@bje- Data ingestion tutorial for the docker image requested by users.

Data ingestion tute

---

utils/api_test.go
utils/config.go

@bje- This is for https://github.com/nci/gsky/issues/179

added timestamps aggregation for mas timestamps

---

ows.go
utils/wms.go
utils/wms_test.go

@bje- I added check against empty timestamps to prevent index out of range exceptions of the `Dates` array

added check against empty timestamps

---

processor/tile_grpc.go
utils/config.go

@bje- this is for https://github.com/nci/gsky/issues/183

added consolidation of small polygon shards

---

config_json.md
ows.go
utils/api_test.go
utils/config.go

@bje- This is for https://github.com/nci/gsky/issues/185

Templated config files

---

mas/api/mas.sql
mas/db/shard.sql
mas/db/shard_create.sh
mas/db/shard_refresh.sh
mas/db/shard_reset.sh

@bje-  this is for https://github.com/nci/gsky/issues/190

added timestamps cache

---

crawl/crawl.go
crawl/extractor/info.go
crawl/extractor/types.go
mas/api/mas.sql
ows.go
processor/drill_grpc.go
processor/drill_indexer.go
processor/drill_pipeline.go
processor/drill_types.go
processor/tile_indexer.go
utils/config.go

@bje- this is for https://github.com/nci/gsky/issues/192

O(1) polygon drill

---

processor/tile_indexer.go

@bje- this PR is required for publishing a new dataset from GA. Previously clients have dedicated data file that provides the masking data but now this dataset needs masking against the raw data.

allows masking against raw data

---

mas/api/api.go
mas/api/mas.sql
ows.go
processor/tile_indexer.go
processor/tile_types.go

@bje-  this is for https://github.com/nci/gsky/issues/196

indicative zoom-in

---

ows.go
testsuite/wget.bats
utils/config.go

@bje- I added checks for max width and height of wms and wcs requests.

added checks for max width and height

---

templates/WCS_DescribeCoverage.tpl
templates/WCS_GetCapabilities.tpl
utils/config.go

@bje- this PR addresses https://github.com/nci/gsky/issues/202 and https://github.com/nci/gsky/issues/201

fixed wcs compliance issues

---

Makefile.in
utils/config.go
worker/gdalprocess/pool.go

fixed gsky-gdal-process path in makefile and removed the unreferenced LibexecDir

fixed gsky-gdal-process path

---

ows.go

added AutotimestampRefresh flag for WCS to allow automatic or manual refresh of timestamps from MAS

added AutoTimestampRefresh for wcs

---

utils/config.go

This fixes https://github.com/nci/gsky/issues/215

Normalised MAS timestamps

---

crawl/extractor/ruleset.go

fixed corner cases for sentinel2 crawling.

fixed corner cases for sentinel2 crawling

---

utils/config.go

made start date inclusive for monthly and regular time generators

made start date inclusive for monthly and regular time generators

---

crawl/extractor/ruleset.go

fixed a few corner cases for extracting the band names for Sentinel 2

fixed sentinel2 crawler band name issues

---

ows.go
processor/tile_extent.go
processor/tile_indexer.go
processor/tile_pipeline.go
utils/config.go

added conditional verbose logging to reduce log outputs

added conditional verbose logging

---

ows.go
processor/feature_info.go
utils/config.go

Added support for GetFeatureInfo. It implements the following functionalities in terriajs's context:
* By default, GetFeatureInfo returns the raw band values for the clicked pixel in question
* Optionally, one can specify max data links greater than zero to retrieve the underlying data file names corresponding to the pixel in question
* Optionally, one can also specify a URL prefixing the data file names. This is meant for generating a download link for the data file e.g. from a thredds server.

Added support for GetFeatureInfo

---

processor/feature_info.go
utils/config.go

added support for getFeatureInfo specific bands

added support for getFeatureInfo specific bands

---

ows.go

This PR fixes https://github.com/nci/gsky/issues/232

added support to infer ows service from request

---

ows.go
processor/date_splitter.go
processor/drill_merger.go
processor/drill_pipeline.go
processor/drill_types.go
utils/config.go

unified wms, wcs and wps band maths

unified wms, wcs and wps band maths

---

ows.go
utils/config.go

added support for dumping the runtime config settings to sanity check what settings actually go into the processing pipeline

added support for dumping the runtime config settings

---

mas/api/mas.sql

sanitised band names for mas_intersects query

sanitised band names for mas_intersects query

---

ows.go
utils/wcs.go

removed default style for wcs as this is not part of the wcs standards.

removed default style for wcs

---

crawl/extractor/info_sentinel2_yaml.go
crawl/extractor/ruleset.go
ows.go

sync with master

---

ows.go
processor/drill_grpc.go
processor/drill_indexer.go
processor/drill_pipeline.go

added support for verbose wps outputs

added support for verbose wps outputs

---

utils/output_encoders.go
utils/raster_scaler.go

added auto offset and scaling for fast prototyping publication of new datasets

added auto offset and scaling

---

worker/gdalprocess/warp.go

Apparently GSKY supports uint8, uint16, int16 and float32. We will need to cast non-supported GDAL data types such as uint32, int32, and float64 into float32.

casting non-supported GDAL data types into float32

---

static/index.html

Some information on GSKY website is outdated. This PR fixes them.

fixed incorrect information of the gsky website

---

ows.go
templates/WPS_DescribeProcess.tpl
utils/wps.go

This PR added support for specifying geometry id as WPS input.

added support for specifying geometry id as wps input

---

crawl/extractor/info.go
gdal-process/main.go
processor/tile_pipeline.go
utils/wcs.go
utils/wms.go

This PR fixes go vet issues which fail travis-ci.

fixed go vet

---

ows.go
templates/WPS_Outputs/geometryDrill/chirps2.0.tpl
templates/WPS_Outputs/geometryDrill/geoglam_fc.tpl

This PR simplifies WPS csv column names according to customer's requirements.

simplify wps csv column names

---

processor/feature_info.go
processor/tile_grpc.go
processor/tile_merger.go
processor/tile_pipeline.go
utils/ogc_encoders.go
utils/raster_scaler.go
worker/gdalprocess/warp.go

This PR adds support for signed byte data type.

added support for signed byte data type

---

utils/config.go

This PR relaxes the requirements for `data_source` for blended layers.

relaxed the requirements for data_source for blended layers

---

utils/config.go

This PR adds support for inheriting input_layers for styles

added support for inheriting input_layers for styles

---

dap.go
ows.go
utils/config.go
utils/wms.go

This PR adds support for disabling certain services. This is required for some layers such as the blended layers which do not support WCS for scientific reasons.

added support for disabling services

---

crawl/extractor/info.go

This PR fixes time dimension crawling logic.

fixed time dimension crawling logic

---

worker/gdalprocess/drill.go

This PR fixes a few numerical issues in WPS deciles.

fixed numerical issues in wps deciles

---

ows.go
utils/config.go

This PR adds support for wms axis mapping for pseudo axes.

added support for wms axis mapping for pseudo axes

---

ows.go

This PR adds support for serving files across domain origins.

added support cors serving files

---

ows.go
utils/config.go
utils/wms.go

This PR adds support for multi-palettes such that users can dynamically switch palettes on the fly. This feature is often requested by geophysicists.

added support for multi-palettes

---

crawl/crawl_pipeline.sh

This PR adds support for outputting raw record from crawl_pipeline.

added support for outputting raw record from crawl_pipeline

---

crawl/crawl.go

This PR adds crawler cmdline switch for netCDF metadata.

added crawler cmdline switch for netCDF metadata

---

Makefile.in

This PR fixes makefile issues in compiling GSKY netCDF driver.

fixed makefile

---

Makefile.in

This PR prioritises prerequisites for make-all.

prioritised prerequisites for make-all

---

mas/api/api.go
mas/api/mas.sql

This PR adds support for computing geospatial and temporal extents.

added support for computing geospatial and temporal extents

---

mas/api/mas.sql

This PR adds support for retrieving variable names from mas.

added support for retrieving variable names from mas

---

ows.go
processor/feature_info.go
processor/tile_pipeline.go
processor/tile_types.go
utils/config.go
utils/ogc_encoders.go
utils/wms.go

This PR adds support for overviews which boost performance at high zoom levels.

added support for overviews

---

utils/config.go

This PR fixes empty namespace for blended layers.

fixed empty namespace for blended layers

---

utils/palette.go

This PR adds support for alpha channel in colour palettes.

added support for alpha channel in colour palettes

---

dap.go
metrics/logger.go
metrics/metrics.go
ows.go
processor/date_splitter.go
processor/drill_grpc.go
processor/drill_indexer.go
processor/drill_types.go
processor/feature_info.go
processor/tile_grpc.go
processor/tile_indexer.go
processor/tile_pipeline.go
processor/tile_types.go
worker/gdalprocess/drill.go

This PR adds support for logging a variety of metrics for understanding request profiles.

added support for logging metrics

---

metrics/logger.go

This PR refines log file patterns to be friendly with log collectors.

refined log file patterns to be friendly with log collectors

---

.travis.yml

This PR fixes travis-ci errors due to outdated dependencies.

fixed travis-ci errors due to outdated dependencies

---

metrics/metrics.go

This PR adds guard against nil logger.

added guard against nil logger

---

processor/tile_pipeline.go

This PR adds support for filtering blended layers by time range, which saves a round trip of MAS query.

added support for filtering blended layers by time range

---

.travis.yml

This PR improves travis-ci buid.

improved travis-ci buid

---

metrics/metrics.go
ows.go
processor/drill_indexer.go
processor/tile_indexer.go

This PR adds more structures for metric logging.

added more structures for metric logging

---

docker/Dockerfile
docker/build_deps.sh
docker/build_gdal.sh
docker/build_gsky.sh
docker/build_pgsql.sh
docker/build_postgis.sh
docker/gsky_config.json
docker/gsky_entry_point.sh

This PR updates the docker build for the latest master branch.

updated docker build

---

.travis.yml

This PR fixes travis-ci build for different branches of GSKY repo.

fixed travis-ci gsky build

---

docker/README.md

This PR updates docker readme.

updated docker readme

---

.travis.yml

This PR fixes travis-ci build regression.

fixed travis-ci build regression

---

utils/gdal_init.go
worker/gdalprocess/warp.go

This PR improves GDALOpenEx() performance.

improved GDALOpenEx() performance

---

metrics/metrics.go
ows.go
utils/url_parser.go

This PR fixes real client IP issue behind reverse proxy.

fixed real client IP behind reverse proxy

---

processor/tile_indexer.go
processor/tile_pipeline.go
utils/wms.go

This PR adds support for performing band maths over the time axis.

added support for band maths over time

---

processor/tile_merger.go
utils/config.go

This PR adds support for blended service per style.

added support for blended service per style

---

processor/tile_indexer.go
utils/wms.go

This PR adds support for non-monotonic axes.

added support for non-monotonic axes

---

utils/wms.go

This PR fixes wms axes merging issue.

fixed wms axes merging issue

---

processor/drill_grpc.go

This PR adds check against nil raster in drill gRPC.

added check against nil raster in drill grpc

---

crawl/extractor/info.go

This PR adds support for crawling fractional days in netCDF files.

added support for crawling fractional days

---

crawl/crawl.go
crawl/extractor/info.go
crawl/extractor/ruleset.go

This PR adds support for matching full path for crawler.

added matching full path for crawler

---

mas/db/ingest_pipeline.sh

This PR adds support for applying filters in mas ingestion pipeline.

added support for applying filters in mas ingestion pipeline

---

processor/tile_pipeline.go
utils/config.go

This PR adds support for recursive blending service.

added support for recursive blending service

---

utils/config.go

This PR adds support for propagating `palette` in fusion layers with single band. This avoids manually copying the `palette` field into the fusion layer from its input layers unless explicitly overriding.

added support for propogating palette in fusion layers

---

utils/config.go

This PR fixes empty namespace issues for fusion layers.

fixed empty namespace for fusion layers

---

metrics/log_format.md

This PR adds documentation for metrics logging.

added documentation for metrics logging

---

processor/feature_info.go
processor/tile_merger.go
processor/tile_pipeline.go

This PR fixes `data_available_dates` returned from `GetFeatureInfo` for the regions without data.

fixed data_available_dates for the regions without data

---

templates/WPS_Outputs/geometryDrill/geoglam_pixel_fraction.tpl

This PR changes the y-axis of the pixel fraction template to use percentage as the unit of measurement.

made using percentage for the y-axis of pixel frac template

---

crawl/extractor/info_yaml.go

This PR makes uses `valid_data` as the bounding box for sentinel 2 files. The `valid_data` geospatial extent is a refined bounding box that only encloses the area with valid pixels. In comparison, the raw geospatial extent is a coarse version of the bounding box that encloses both valid and invalid pixels.

made use of valid_data polygon for sentinel 2

---

ows.go

This PR adds support for multi-timestamps for `getFeatureInfo`

added support for multi-timestamps for getFeatureInfo

---

metrics/logger.go
metrics/metrics.go
ows.go

This PR adds support for compressing rotated log files to save storage space.

added support for compressing rotated log files

---

libs/gdal/frmts/gsky_netcdf/netcdfdataset.cpp

This PR fixed couple of potential memory leaks in the netCDF driver.

fixed netcdf memory leaks

---

mas/db/shard.sql

This PR removes unused mas objects used for testing purpose.

removed unused mas objects

---

README.md
static/index.html

This PR updates copyright years.

updated copyright years

---

crawl/extractor/info.go

This PR fixes a race condition in concurrent crawls of netCDF subdatasets.

fixed race condition in concurrent crawls

---

crawl/crawl.go
crawl/extractor/info.go

This PR prunes unnecessary outputs from GDAL crawls.

pruned gdal crawl outputs

---

dap.go
ows.go
templates/WMS_GetCapabilities.tpl
utils/config.go

This PR adds support to derive ows_hostname from http headers. This PR addresses https://github.com/nci/gsky/issues/379

added support to derive ows_hostname from http headers

---

utils/wps.go
worker/gdalprocess/drill.go

This PR fixes several memory leaks in the WPS pipeline.

fixed WPS memory leaks

---

metrics/metrics.go

This PR surpresses warning message for `OGR_G_Area()` on non-surface geometry by checking its input geometry type.

surpressed warning message for OGR_G_Area() on non-surface geometry

---

worker/gdalprocess/vrt_manager.go

This PR adds default values for dynamic VRT.

added default values for dynamic VRT

---

processor/tile_indexer.go
utils/wms.go

This PR obtains a canonical bbox before comparing against `IndexResLimit`

obtained canonical bbox before comparing against IndexResLimit

---

processor/drill_indexer.go

This PR checks for duplicated granules for spatial-temporal hash key. If there are duplicated granules for the same spatial-temporal hash key, it's likely due to issues in the underlying dataset. Having said that, we still have to deal with the situation.

checked for duplicated granules for spatial-temporal hash key

---

worker/gdalprocess/vrt_manager.go

This PR rescales GeoTransform entries for subsampled VRT.

rescaled GeoTransform entries for subsampled VRT

---

worker/gdalprocess/process.go

This PR adds support for retrying failed tasks up to hard-coded 5 times for each worker process.

added support for retrying failed tasks

---

templates/WPS_Outputs/geometryDrill/landsat3_ndvi.tpl
templates/WPS_Outputs/geometryDrill/landsat3_ndwi.tpl
templates/WPS_Outputs/geometryDrill/sentinel2_ndci.tpl
templates/WPS_Outputs/geometryDrill/sentinel2_ndvi.tpl
templates/WPS_Outputs/geometryDrill/sentinel2_ndwi.tpl

This PR adds a few indices templates for Landsat 3 and Sentinel 2.

added indices templates for landsat3 and sentinel2

---

processor/drill_grpc.go
processor/drill_merger.go
processor/drill_types.go
worker/gdalprocess/drill.go

This PR takes `NoData` into account after evaluating WPS band expressions.

taking nodata into account for WPS band expressions

---

ows.go
processor/date_splitter.go
processor/drill_grpc.go
processor/drill_indexer.go
processor/drill_types.go
utils/config.go

This PR adds support for dynamically querying number of workers for WPS.

added support for dynamically querying number of workers for WPS

---

ows.go
processor/date_splitter.go
processor/drill_indexer.go
processor/drill_types.go

This PR adds tiled indexer for WPS. This is to tile the spatial extent in large request and send each tile to the PostGIS indexer backend. With this feature, the PostGIS indexer backend can now handle arbitrarily large request.

added tiled indexer for WPS

---

processor/drill_grpc.go

This PR streamlines WPS gRPC processing. This feature allows WPS gRPC processing interleaving with tiled indexer query, which is essential for the requested geo-spatial extent in arbitrarily large size.

streamlined WPS gRPC processing

---

processor/drill_merger.go
processor/drill_pipeline.go

This PR added support for cancellation of operations in `drill_merger`.

added support for cancellation of operations in drill_merger

---

processor/drill_indexer.go
utils/config.go

This fixed CI build of jet template engine.

fixed build of jet template engine

---

worker/gdalprocess/drill.go

This PR fixes a few memory issues in WPS drill worker.

fixed memory issues in WPS drill worker

---

worker/gdalprocess/drill.go

This PR reduces memory usage of drill polygon rasterisation. This also boosts performance due to less region to rasterise.

reduced memory usage of drill polygon rasterisation

---

processor/drill_indexer.go

This PR provides more accurate accounting for WPS indexer timing.

better accounting for WPS indexer timing

---

utils/wps.go

This PR removes SRS in WPS area calculations.

removed SRS in WPS area calculations

---

gdal-process/main.go
grpc-server/main.go
worker/gdalprocess/pool.go
worker/gdalprocess/process.go
worker/gdalprocess/warp.go

This PR improves consistency of verbosity of the gRPC workers.

improved consistency of verbosity of the grpc workers

---

ows.go
processor/tile_grpc.go
processor/tile_indexer.go
worker/gdalprocess/warp.go

This PR provides more accurate accounting for the timing statistics in WMS and WCS pipeline.

better account for timing in WMS/WCS pipeline

---

mas/api/mas.sql

This PR works around crs not found for `proj_create()` since proj 6.0.0.

worked around crs not found for proj_create() since proj 6.0.0

---

processor/tile_grpc.go

This PR avoids computing geo-transform repeatedly in WMS/WCS pipeline.

avoided computing geo-transform repeatedly

---

crawl/extractor/info.go

This PR avoids loading all bands but the first band when crawling data files. The metadata required by GSKY are the same among all bands. By only loading the first band, the data files can be crawled in constant time regardless of the number of bands.

crawler avoids loading all bands 

---

processor/tile_grpc.go
processor/tile_indexer.go
processor/tile_merger.go
processor/tile_pipeline.go

This PR improves cancellation support for WMS/WCS pipeline.

better cancellation support for WMS/WCS pipeline

---

ows.go

This PR adds support to show ows listening host.

added support to show ows listening host

---

processor/tile_grpc.go
processor/tile_types.go

This PR fixes the calculation of target GeoTransform for tiled gRPC requests.

fixed target GeoTransform for tiled gRPC

---

mas/db/shard.sql

This PR adds support for asynchronous commit of ingestion transactions. This improves performance in parallel ingestion.

added support for async commit of ingestion transactions

---

ows.go
utils/config.go

This PR adds timeout for WPS pipeline.

added timeout for WPS pipeline

---

templates/WPS_VRTs/masks_example.vrt

This PR improves the example VRT.

improved example vrt

---

processor/drill_indexer.go

This PR adds verbosity for WPS `RasterXSize` and `RasterYSize`.

added verbosity for wps raster sizes

---

processor/tile_pipeline.go

This PR enables concurrent processing of file list for `GetFeatureInfo` for blended layers.

enabled concurrent processing of file list for GetFeatureInfo

---

mas/api/mas.sql
mas/db/shard.sql
mas/db/shard_refresh.sh

This PR reverts incremental updates on shards. The approach employed by incremental updates on shards does not cope with MODIS sinusoidal projections.

reverted incremental updates on shards

---

processor/drill_grpc.go

This PR adds guards against closed output channel for drill gRPC.

added guards against closed output channel for drill grpc

---

crawl/crawl_pipeline.sh

This PR adds gzip compression for crawl file list.

added gzip compression for crawl file list

---

worker/gdalprocess/vrt_manager.go

This PR adds support for customising VRT band data type.

added support for customising VRT band data type

---

crawl/crawl.go
crawl/extractor/info_posix.go
crawl/extractor/types.go

added posix crawler

---

crawl/extractor/info_posix.go

This PR fixes output format for the POSIX crawler.

fixed output format for posix crawler

---

crawl/crawl_pipeline.sh

This PR counting the crawl file list with gzip compression.

properly counting gzip crawl file list

---

crawl/crawl.go
crawl/extractor/info_posix.go

This PR adds support for evaluating a boolean expression for file pattern matching in the POSIX crawler.

added pattern expression for posix crawler

---

libs/gdal/frmts/gsky_netcdf/netcdfdataset.cpp

This PR adds guards against nan and inf in netCDF.

added guards against nan and inf in netCDF

---

libs/gdal/frmts/gsky_netcdf/netcdfdataset.cpp

This PR adds support for mapping 1D netCDF variables onto 2D 1x1 planes.

added support for 1D netCDF variables

---

libs/gdal/frmts/gsky_netcdf/netcdfdataset.cpp

This PR adds `sd_query` open option to netCDF driver to enable querying subdatasets regardless of number of raster variables. This facilitates more consistent handling of subdatasets when crawling netCDF files.

added subdatasets query only

---

libs/gdal/frmts/gsky_netcdf/netcdfdataset.cpp

This PR fixes band metadata for 1D netCDF variable.

fixed band metadata for 1D netCDF variable

---

libs/gdal/frmts/gsky_netcdf/netcdfdataset.cpp
libs/gdal/frmts/gsky_netcdf/netcdfdataset.h

This PR adds support for looking up netCDF main variable from user-specified metadata.

added netCDF main variable lookup from metadata

---

libs/gdal/frmts/gsky_netcdf/netcdfdataset.cpp

This PR adds support for warping longitude into [-180, 180] for geolocation array.

added support for warping longtitude for geolocation array

---

crawl/extractor/info_posix.go

This PR optimises scheduling of POSIX crawling tasks.

optimised scheduling of posix tasks

---

ows.go
utils/config.go

This PR adds thread-safe config reloading.

added thread-safe config reloading

---

mas/db/shard_ingest.sh
mas/db/shard_refresh.sh
mas/db/shard_reset.sh

This PR enables concurrent updates on MAS while dataset is being ingested, which improves uptime of MAS.

added concurrent updates on MAS

---

utils/config.go

This PR adds support for using search path for loading config files.

added search path for loading config files

---

ows.go
static/index.html

This PR adds dynamic footer for the landing page of GSKY website. The dynamic footer automatically keeps the copyright year up to date.

added dynamic footer for the landing page of GSKY website

---

libs/gdal/frmts/gsky_netcdf/netcdfdataset.cpp

This PR implements a fast version of `strcat()` for building netCDF 1D value string. With the original `strcat()`, the time complexity of concatenating multiple strings is O(n^2). In comparison, the fast version is O(n).

implemented fast strcat for building netCDF 1D value string

---

docker/Dockerfile

This PR adds `bc` to docker image.

added bc to docker image

---

processor/feature_info.go

This PR fixes projection issues in `getFeatureInfo`

fixed projection in getFeatureInfo

---

utils/ogc_encoders.go

This PR adds NC4C netCDF format for WCS.

added NC4C netCDF format for WCS

---

templates/WMS_GetCapabilities.tpl

This PR removes unused formats for `FeatureInfo`

removed unused formats for FeatureInfo

---

templates/WMS_GetCapabilities.tpl

This PR removes CRS:84 support.

removed CRS:84

---

utils/url_parser.go
utils/wcs.go
utils/wms.go

This PR adds HTTP parameter `code`. This parameter facilitates user-defined band math.

added http parameter code

---

processor/feature_info.go

This PR adds user-defined code for `getFeatureInfo`.

added user code for getFeatureInfo

---

utils/wcs.go
utils/wms.go

This PR adds code_format for user-defined band math.

added code_format for user-defined band math

---

ows.go
processor/feature_info.go
utils/config.go

This PR adds complexity constraints on user-defined band math.

added complexity constraints on user-defined band math

---

.travis.yml

This PR fixes travis-ci build.

fixed travis-ci build

---

templates/WMS_GetCapabilities.tpl
utils/config.go

This PR adds support for available bands for band math in GetCapabilities.

added available bands for band math in GetCapabilities

---

utils/wms.go

This PR fixes the endpoint issues for `colorscalerange`.

fixed colorscalerange endpoint issues

---

ows.go

This PR fixes issues in user-defined band math expression with a single band.

fixed single-banded math expression

---

ows.go
utils/config.go

This PR adds support for loading configs on-demand. This feature is required for handling large number of namespaces.

loading configs on-demand

---

utils/config.go

This PR adds token ACL for user-defined band math.

added token ACL for user-defined band math

---

utils/config.go

This PR adds added constraints on supported band variables for user-defined band math

added constraints on supported band variables for user-defined band math

---

ows.go
templates/WCS_GetCapabilities.tpl
templates/WMS_DescribeLayer.tpl
templates/WMS_GetCapabilities.tpl
templates/WPS_GetCapabilities.tpl
utils/config.go
utils/url_parser.go

This PR adds support for deriving endpoint protocols.

added support for deriving endpoint protocols

---

README.md

This PR updates copyright year.

updated copyright year

---

static/index.html

This PR updates the URL for GSKY docs.

updated URL for GSKY docs

---

static/index.html

This PR opens hyperlinks on GSKY home page in new browser tabs.

open hyperlinks in new browser tab

---

mas/api/mas.sql

This PR adds support for listing sub gpaths and namespaces.

added support for listing sub gpaths and namespaces

---

mas/api/mas.sql

This PR fixes jsonb_build_object(null) error.

fixed jsonb_build_object(null) error

---

ows.go
utils/catalogues.go
utils/url_parser.go

This PR adds support for rendering `{{ .Host }}` variable for the index pages.

rendering Host variable for index pages

---

Makefile.in
ows.go
utils/config.go

This PR adds version information for GSKY. `ows -version` will print out the git commit of the build.

added version information

---

mas/db/shard.sql

This PR enables parallel query for generating the materialised view for polygons.

enabled parallel query for polygon view

---

ows.go

This PR adds verbosity for LoadConfigOnDemand error.

added verbosity for LoadConfigOnDemand error

---

crawl/extractor/info.go
crawl/extractor/info_posix.go
crawl/extractor/info_yaml.go
crawl/extractor/types.go

This PR adds POSIX info for the content crawlers.

added posix info for content crawler

---

ows.go
processor/tile_indexer.go

This PR improves robustness of high concurrent access to MAS.

improved robustness of high concurrent access to MAS

---

utils/config.go

This PR fixes layer namespace for configs loaded on-demand.

fixed layer namespace for configs loaded on-demand

---

mas/api/mas.sql
mas/db/shard.sql

This PR improves time range indexing using `tstzrange` data type to represent the time range.

improved time range indexing using tstzrange

---

mas/api/api.go
mas/api/mas.sql
mas/db/shard.sql

This PR removes pixel resolution from MAS since this parameter is never used.

removed pixel resolution from MAS

---

mas/api/mas.sql
mas/db/shard.sql
mas/db/shard_create.sh
mas/db/shard_refresh.sh

This PR adds code generation for optimising the performance of shard specific queries.

added codegen for MAS intersects queries

---

mas/api/mas.sql
mas/db/shard.sql

This PR changes from drop to create or replace functions. This is for compatibility for old versions of PostgreSQL.

changed from drop to create or replace functions

---

ows.go
processor/feature_info.go
processor/tile_pipeline.go

This PR fixes overview zoom limits when the corresponding layer zoom limit is zero.

fixed overview zoom limits

---

ows.go
utils/config.go

This PR fixes on-demand timestamps loading for blended layers.

fixed on-demand timestamps for blended layers

---

README.md

This PR removes copyright end date so that we don't have to update it every year.

removed copyright end date

---

ows.go
processor/feature_info.go
utils/config.go

This PR fixes lazy-loading issues for on-demand timestamps.

fixed lazy-loading issues for on-demand timestamps

---

ows.go

This PR standardises ows_cache query key for WMS.

standardised ows_cache query key for WMS

---

README.md

This PR adds docker information to readme.

added docker information to readme

---

README.md

improved readme text

---

ows.go
utils/config.go

This PR adds support for inheriting cluster information from ancestor namespaces.

added support for inheriting cluster information from ancestor namespaces

---

grpc-server/main.go
ows.go

This PR removes pprof for performance.

removed pprof

---

worker/gdalprocess/warp.go

This PR improves efficiency in overview proj transform.

improved efficiency in overview proj transform

---

worker/gdalprocess/warp.go

This PR removes hard-coded CPPFLAGS

removed hard-coded CPPFLAGS

---

go.mod
go.sum

This PR fixes go module for band math.

fixed go module for band math

---

docker/build_gsky.sh

This PR fixes go module for GSKY docker build.

fixed go module in GSKY docker build

---

README.md

This PR updates readme for go modules.

readme updates for go modules

---

Makefile.in

This PR migrates the git repo for concurrent utility.

migrated git repo for concurrent utility

---

docker/build_gsky.sh

This PR fixes go modules issues for build_gsky.sh.

fixed go modules for build_gsky.sh

---

worker/gdalprocess/warper.cxx

This PR adds const qualifier to immutable variables .

added const qualifier to immutable variables

---

ows.go
templates/WCS_GetCapabilities.tpl

This PR adds WCS timepositions.

added WCS timepositions

---

libs/gdal/frmts/gsky_netcdf/netcdfdataset.cpp

This PR fixes netCDF raster variable lookup.

fixed netCDF raster variable lookup

---

libs/gdal/frmts/gsky_netcdf/netcdfdataset.cpp

This PR fixes netCDF variable lookup for 1D raster variables.

fixed netCDF variable lookup for 1D raster variables

---

libs/gdal/frmts/gsky_netcdf/netcdfdataset.cpp

This PR fixes netCDF subdataset query for a single raster variable.

fixed netCDF subdataset query for a single raster variable

---

worker/gdalprocess/drill.go

This PR fixes geometry drill error message.

fixed geodrill error message

---

libs/gdal/frmts/gsky_netcdf/netcdfdataset.cpp

This PR adds precedence for main netCDF variable lookup.

added precedence for main netCDF variable lookup

---

worker/gdalprocess/warp.go
worker/gdalprocess/warper.cxx
worker/gdalprocess/warper.hxx

This PR fixes integer overflow in `bytesRead`.

fixed integer overflow in bytesRead
